/* The Bukit Besi v3.1 core — navigation, panels, TOC, related fallback, content safety. Zero jQuery. */
(() => {
  'use strict';
  const one=(s,r=document)=>r.querySelector(s);
  const all=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const setting=(text,key)=>String(text||'').match(new RegExp('\\$'+key+'=\\{([^}]*)\\}','i'))?.[1].trim()||'';
  const safeURL=(value,base=location.href)=>{if(!value)return'';try{const u=new URL(value,base);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
  const cfg=typeof pbt==='object'&&pbt?pbt:{};
  const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
  const reducedMotion=()=>matchMedia?.('(prefers-reduced-motion: reduce)').matches;
  let body,activePanel=null,returnFocus=null,jsonpId=0;

  function origin(){const base=one('link[rel="canonical"]')?.href||location.href;return new URL(base,location.href).origin}
  function searchURL(label=''){return new URL(label&&!['recent','random'].includes(label)?'/search/label/'+encodeURIComponent(label):'/search',origin()).href}

  function menuTree(nav){
    if(!nav||nav.dataset.tbbTree==='1')return; nav.dataset.tbbTree='1';
    const items=Array.from(nav.children).filter(el=>el.tagName==='LI'),parents=[];
    items.forEach(li=>{const link=one(':scope > a',li);if(!link)return;const text=link.textContent.trim(),depth=Math.min(text.match(/^_+/)?.[0].length||0,2);link.textContent=text.replace(/^_+/,'');const parent=parents[depth-1];if(depth&&parent){let sub=one(':scope > ul.sub',parent);if(!sub){sub=document.createElement('ul');sub.className='ul sub sm-'+depth;parent.append(sub)}sub.append(li);parent.classList.add('has-sub')}parents[depth]=li;parents.length=depth+1});
    nav.closest('.widget')?.classList.add('is-ready');
  }

  function mobileFromDesktop(source,dest){
    if(!source||!dest||dest.children.length)return;const nav=source.cloneNode(true);nav.className='mobile-nav';all('[id]',nav).forEach(el=>el.removeAttribute('id'));
    all('.has-mega',nav).forEach(li=>{const a=one(':scope > a',li);const labels=(setting(a?.dataset.shortcode||'','label')||'').split('/').map(s=>s.trim()).filter(Boolean);one(':scope > .mega',li)?.remove();if(labels.length){let sub=one(':scope > ul.sub',li);if(!sub){sub=document.createElement('ul');sub.className='sub';li.append(sub)}labels.forEach(label=>{const item=document.createElement('li'),link=document.createElement('a');link.href=searchURL(label);link.textContent=label;item.append(link);sub.append(item)})}li.classList.remove('has-mega','type-mega');li.classList.add('has-sub')});
    all('ul.sub',nav).forEach(ul=>ul.className='sub');
    all('.has-sub > a',nav).forEach(a=>{a.setAttribute('aria-expanded','false');a.addEventListener('click',e=>{const li=a.parentElement;if(!one(':scope > ul.sub',li))return;e.preventDefault();const on=li.classList.toggle('expanded');a.setAttribute('aria-expanded',String(on))})});
    dest.append(nav);
  }

  function hydrateDrawerFooter(){const footer=one('.mm-footer');if(!footer||footer.children.length)return;const social=one('.footer-info .social');if(social){const clone=social.cloneNode(true);clone.className='social color';all('[id]',clone).forEach(el=>el.removeAttribute('id'));all('.text',clone).forEach(el=>el.remove());footer.append(clone)}const links=one('.footer-menu ul');if(links){const clone=links.cloneNode(true);clone.className='links';all('[id]',clone).forEach(el=>el.removeAttribute('id'));footer.append(clone)}}
  function initMenus(){const source=one('#main-menu .main-nav')||one('.main-nav');if(source)menuTree(source);one('#main-menu .widget')?.classList.add('is-ready');mobileFromDesktop(source,one('.mobile-menu'));const logo=one('.main-logo a'),slot=one('.mobile-logo');if(logo&&slot&&!slot.children.length){const clone=logo.cloneNode(true);all('[id]',clone).forEach(el=>el.removeAttribute('id'));slot.append(clone)}hydrateDrawerFooter()}

  function focusables(box){return all('a[href],button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex="0"]',box).filter(el=>el.getClientRects().length)}
  function panel(name,trigger){const opening=!!name&&activePanel!==name;body.classList.remove('menu-on','search-on','share-on');all('.menu-toggle').forEach(el=>el.setAttribute('aria-expanded','false'));if(!opening){const old=returnFocus;activePanel=null;returnFocus=null;old?.focus?.();return}activePanel=name;returnFocus=trigger||document.activeElement;body.classList.add(name+'-on');if(name==='menu')all('.menu-toggle').forEach(el=>el.setAttribute('aria-expanded','true'));requestAnimationFrame(()=>{const box=one(name==='menu'?'.slide-menu':name==='search'?'.main-search':'.share-modal');focusables(box||document)[0]?.focus()})}
  function initPanels(){all('.menu-toggle').forEach(el=>el.addEventListener('click',()=>panel('menu',el)));all('.search-toggle').forEach(el=>el.addEventListener('click',()=>panel('search',el)));all('.share-toggle,.post-share .show-more button').forEach(el=>el.addEventListener('click',()=>panel('share',el)));all('.overlay-bg,.hide-mobile-menu,.main-search .close,.hide-modal').forEach(el=>el.addEventListener('click',()=>panel(null)));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&activePanel)return panel(null);if(e.key!=='Tab'||!activePanel)return;const box=one(activePanel==='menu'?'.slide-menu':activePanel==='search'?'.main-search':'.share-modal');if(!box)return;const controls=focusables(box);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}})}

  function initDarkMode(){const root=document.documentElement,stored=storage.get('tbb_dark_mode')??storage.get('dark_mode');if(cfg.isDark===true||stored==='true')root.classList.add('is-dark');const sync=()=>{const dark=root.classList.contains('is-dark');all('.darkmode-toggle').forEach(el=>el.setAttribute('aria-pressed',String(dark)))};sync();all('.darkmode-toggle').forEach(el=>el.addEventListener('click',()=>{root.classList.toggle('is-dark');storage.set('tbb_dark_mode',String(root.classList.contains('is-dark')));sync()}))}
  function initScroll(){const header=one('.header-inner'),buttons=all('.to-top');let previous=scrollY,ticking=false;const update=()=>{const y=scrollY;if(header&&cfg.stickyMenu!==false){const fixed=y>header.offsetHeight*2;header.classList.toggle('is-fixed',fixed);header.classList.toggle('show',fixed&&y<previous)}buttons.forEach(el=>el.classList.toggle('show',y>=100));previous=y;ticking=false};addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}},{passive:true});buttons.forEach(el=>el.addEventListener('click',()=>scrollTo({top:0,behavior:reducedMotion()?'auto':'smooth'})))}

  function slugify(text){return String(text||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\u00C0-\u024f\u0600-\u06ff]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,80)||'section'}
  function tocMarker(post){const walker=document.createTreeWalker(post,NodeFilter.SHOW_TEXT,{acceptNode(node){if(!node.nodeValue?.includes('{getToc}'))return NodeFilter.FILTER_REJECT;const p=node.parentElement;if(!p||p.closest('script,style,noscript,.tbb-toc'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const node=walker.nextNode();if(!node)return null;const text=node.nodeValue||'',start=text.indexOf('{getToc}');let end=text.length;const nextBrace=text.indexOf('\n',start);if(nextBrace>-1)end=nextBrace;return{node,text:text.slice(start,end).trim()||'{getToc}'}}
  function buildToc(post){if(!post||post.dataset.tbbToc==='1')return;const found=tocMarker(post);if(!found)return;const headings=all('h2,h3,h4',post).filter(h=>!h.closest('.tbb-toc'));if(!headings.length){found.node.nodeValue=found.node.nodeValue.replace(found.text,'');post.dataset.tbbToc='1';return}const used=new Set(),details=document.createElement('details');details.className='tbb-toc';const expanded=setting(found.text,'expanded').toLowerCase();details.open=['true','1','yes'].includes(expanded);const summary=document.createElement('summary');summary.textContent=setting(found.text,'title')||'Isi Kandungan';const list=document.createElement('ol');list.className='tbb-toc-list';headings.forEach((heading,index)=>{let id=heading.id||slugify(heading.textContent),base=id,n=2;while(used.has(id)||(!heading.id&&document.getElementById(id)))id=base+'-'+n++;used.add(id);heading.id=id;const li=document.createElement('li');li.className='toc-'+heading.tagName.toLowerCase();const a=document.createElement('a');a.href='#'+encodeURIComponent(id);a.textContent=heading.textContent.trim()||('Seksyen '+(index+1));li.append(a);list.append(li)});details.append(summary,list);const before=found.node.nodeValue.slice(0,found.node.nodeValue.indexOf('{getToc}')),after=found.node.nodeValue.slice(found.node.nodeValue.indexOf('{getToc}')+found.text.length);const frag=document.createDocumentFragment();if(before)frag.append(document.createTextNode(before));frag.append(details);if(after)frag.append(document.createTextNode(after));found.node.parentNode.replaceChild(frag,found.node);post.dataset.tbbToc='1'}
  function initToc(){all('.post-body').forEach(buildToc)}

  function resizedThumb(value,w=480,h=270){const raw=safeURL(value,origin());if(!raw)return'';const u=new URL(raw),host=u.hostname.toLowerCase();if(!/(^|\.)(googleusercontent\.com|blogspot\.com|ggpht\.com)$/.test(host))return raw;const size=`w${w}-h${h}-p-k-no-nu-rw`;u.pathname=u.pathname.replace(/\/(?:s\d+(?:-[a-z0-9-]+)?|w\d+(?:-h\d+)?(?:-[a-z0-9-]+)?)\//i,'/'+size+'/');let href=u.href;if(/\/img\/a\/|\/blogger_img_proxy\//.test(u.pathname)||/=(?:s|w)\d+/i.test(href))href=href.replace(/=(?:s\d+|w\d+(?:-h\d+)?)(?:-[a-z0-9-]+)?(?:$|(?=[?#]))/i,'='+size);return href}
  function mapRelated(entry){const url=safeURL(entry.link?.find(l=>l.rel==='alternate')?.href,origin());if(!url)return null;const doc=new DOMParser().parseFromString(entry.summary?.$t||entry.content?.$t||'','text/html');const thumb=resizedThumb(entry.media$thumbnail?.url||one('img',doc)?.getAttribute('src')||cfg.noThumb);return{id:(entry.id?.$t||'').split('post-').pop(),url,title:entry.title?.$t||cfg.noTitle||'Untitled',thumb}}
  function jsonpFeed(label,count){return new Promise((resolve,reject)=>{const u=new URL('/feeds/posts/default'+(label&&label!=='recent'?'/-/'+encodeURIComponent(label):''),origin());u.searchParams.set('alt','json-in-script');u.searchParams.set('max-results',String(Math.max(1,Math.min(20,count))));const cb='__tbbRelated31_'+Date.now().toString(36)+'_'+(++jsonpId),tag=document.createElement('script');let done=false;const clean=()=>{if(done)return;done=true;clearTimeout(timer);tag.remove();try{delete window[cb]}catch{window[cb]=undefined}};const timer=setTimeout(()=>{clean();reject(new Error('Related JSONP timeout'))},7000);window[cb]=data=>{try{const posts=(data?.feed?.entry||[]).map(mapRelated).filter(Boolean);clean();resolve(posts)}catch(e){clean();reject(e)}};u.searchParams.set('callback',cb);tag.async=true;tag.src=u.href;tag.onerror=()=>{clean();reject(new Error('Related JSONP failed'))};document.head.append(tag)})}
  async function relatedFeed(label,count){const u=new URL('/feeds/posts/default'+(label&&label!=='recent'?'/-/'+encodeURIComponent(label):''),origin());u.searchParams.set('alt','json');u.searchParams.set('max-results',String(Math.max(1,Math.min(20,count))));const c=new AbortController(),timer=setTimeout(()=>c.abort(),4500);try{const r=await fetch(u.href,{signal:c.signal,credentials:'omit'});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();return(j.feed?.entry||[]).map(mapRelated).filter(Boolean)}catch{return jsonpFeed(label,count)}finally{clearTimeout(timer)}}
  function renderRelated(target,posts){target.replaceChildren();const box=document.createElement('div');box.className='related-items';posts.forEach(p=>{const article=document.createElement('article');article.className='post';const a=document.createElement('a');a.className='entry-thumbnail';a.href=p.url;a.setAttribute('aria-label',p.title);const thumb=document.createElement('div');thumb.className='thumbnail pbt-lazy';if(p.thumb)thumb.style.backgroundImage='url('+JSON.stringify(p.thumb)+')';a.append(thumb);const head=document.createElement('div');head.className='entry-header';const h=document.createElement('h2');h.className='entry-title';const t=document.createElement('a');t.href=p.url;t.textContent=p.title;h.append(t);head.append(h);article.append(a,head);box.append(article)});target.append(box);target.dataset.tbbState='loaded'}
  async function ensureRelated(wrap){if(!wrap?.isConnected||wrap.dataset.tbbFallback==='1')return;wrap.dataset.tbbFallback='1';const tag=one('.related-tag',wrap),target=one('.widget-content',wrap);if(!tag||!target)return;const code=one('#related-posts .HTML')?.dataset.shortcode||'',count=Math.max(1,Math.min(12,parseInt(setting(code,'results'),10)||6)),existing=all('.related-items .post',target).length;if(existing>=count)return;const labels=(tag.dataset.labels||tag.dataset.label||'').split('||').map(s=>s.trim()).filter(Boolean),ordered=[...new Set([...labels,'recent'])],exclude=String(tag.dataset.id||''),seen=new Set(),posts=[];for(const label of ordered){try{const batch=await relatedFeed(label,Math.max(count+2,8));for(const p of batch){if(String(p.id)===exclude||seen.has(p.url))continue;seen.add(p.url);posts.push(p);if(posts.length>=count)break}}catch{}if(posts.length>=count)break}if(posts.length){renderRelated(target,posts.slice(0,count));const link=one('.title-link',wrap);if(link)link.href=searchURL(labels[0]||'recent')}else{delete wrap.dataset.tbbFallback}}
  function initRelatedFallback(){const wraps=all('.related-wrap');if(!wraps.length)return;const launch=wrap=>setTimeout(()=>ensureRelated(wrap),1200);if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){io.unobserve(e.target);launch(e.target)}}),{rootMargin:'700px'});wraps.forEach(w=>io.observe(w))}else wraps.forEach(launch)}

  function initContent(){all('.post-body img').forEach(img=>{img.decoding='async';if(!img.hasAttribute('loading')&&img.getBoundingClientRect().top>=innerHeight)img.loading='lazy'});all('.post-body table').forEach(table=>{if(table.parentElement?.classList.contains('table-responsive-wrapper'))return;const wrap=document.createElement('div');wrap.className='table-responsive-wrapper';table.before(wrap);wrap.append(table)});all('a.window-open').forEach(link=>{if(!safeURL(link.getAttribute('href')))return;link.target='_blank';link.rel='noopener noreferrer'})}

  function start(){body=document.body;if(!body||body.dataset.tbbCore==='3.1.0')return;body.dataset.tbbCore='3.1.0';[initMenus,initPanels,initDarkMode,initScroll,initToc,initContent,initRelatedFallback].forEach(init=>{try{init()}catch(error){console.error('TBB core '+init.name,error)}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
