/* TBB v4 core — navigation, panels, auto TOC, portable links, share, images, a11y. Zero jQuery. */
(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const setting=(t,k)=>String(t||'').match(new RegExp('\\$'+k+'=\\{([^}]*)\\}','i'))?.[1].trim()||'';
const slug=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\u00c0-\u024f\u0600-\u06ff]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,90)||'section';
const safe=u=>{try{const x=new URL(u,location.href);return /^https?:$/.test(x.protocol)?x.href:''}catch{return''}};
const body=()=>document.body;
function tree(nav){if(!nav||nav.dataset.v4Tree)return;nav.dataset.v4Tree='1';const parents=[];[...nav.children].filter(x=>x.tagName==='LI').forEach(li=>{const a=q(':scope>a',li);if(!a)return;const txt=a.textContent.trim(),d=Math.min((txt.match(/^_+/)||[''])[0].length,2);a.textContent=txt.replace(/^_+/,'');const p=parents[d-1];if(d&&p){let ul=q(':scope>ul.sub',p);if(!ul){ul=document.createElement('ul');ul.className='sub';p.append(ul)}ul.append(li);p.classList.add('has-sub')}parents[d]=li;parents.length=d+1})}
function menu(){const src=q('#main-menu .main-nav')||q('.main-nav');if(src)tree(src);const dest=q('.mobile-menu');if(src&&dest&&!dest.children.length){const nav=src.cloneNode(true);nav.className='mobile-nav';qa('[id]',nav).forEach(x=>x.removeAttribute('id'));qa('.has-mega',nav).forEach(li=>{q(':scope>.mega',li)?.remove();li.classList.remove('has-mega');li.classList.add('has-sub')});qa('.has-sub>a',nav).forEach(a=>{a.setAttribute('aria-expanded','false');a.addEventListener('click',e=>{const li=a.parentElement;if(!q(':scope>ul.sub',li))return;e.preventDefault();const on=li.classList.toggle('expanded');a.setAttribute('aria-expanded',String(on))})});dest.append(nav)}const logo=q('.main-logo a'),slot=q('.mobile-logo');if(logo&&slot&&!slot.children.length)slot.append(logo.cloneNode(true))}
let active=null,returnFocus=null;function panel(name,trigger){const b=body();if(!b)return;const open=!!name&&active!==name;b.classList.remove('menu-on','search-on','share-on');qa('.menu-toggle').forEach(x=>x.setAttribute('aria-expanded','false'));if(!open){const f=returnFocus;active=returnFocus=null;f?.focus?.();return}active=name;returnFocus=trigger||document.activeElement;b.classList.add(name+'-on');if(name==='menu')qa('.menu-toggle').forEach(x=>x.setAttribute('aria-expanded','true'));requestAnimationFrame(()=>{const box=q(name==='menu'?'.slide-menu':name==='search'?'.main-search':'.share-modal');q('a[href],button,input,select,textarea,[tabindex="0"]',box||document)?.focus()})}
function panels(){qa('.menu-toggle').forEach(x=>x.addEventListener('click',()=>panel('menu',x)));qa('.search-toggle').forEach(x=>x.addEventListener('click',()=>panel('search',x)));qa('.share-toggle,.post-share .show-more button').forEach(x=>x.addEventListener('click',()=>panel('share',x)));qa('.overlay-bg,.hide-mobile-menu,.main-search .close,.hide-modal').forEach(x=>x.addEventListener('click',()=>panel(null)));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active)panel(null)})}
function dark(){const root=document.documentElement;let v=null;try{v=localStorage.getItem('tbb_dark_mode')}catch{}if(v==='true')root.classList.add('is-dark');qa('.darkmode-toggle').forEach(btn=>{btn.setAttribute('aria-pressed',String(root.classList.contains('is-dark')));btn.addEventListener('click',()=>{root.classList.toggle('is-dark');const on=root.classList.contains('is-dark');btn.setAttribute('aria-pressed',String(on));try{localStorage.setItem('tbb_dark_mode',String(on))}catch{}})})}
function images(){const els=qa('.thumbnail[data-src],.avatar[data-src]');const load=el=>{if(el.dataset.v4Img)return;el.dataset.v4Img='1';const src=safe(el.dataset.src);if(!src)return;const im=new Image();im.decoding='async';if(el.closest('.featured'))im.fetchPriority='high';im.onload=()=>{el.style.backgroundImage='url('+JSON.stringify(im.src)+')';el.classList.add('pbt-lazy')};im.src=src};if(!('IntersectionObserver'in window)){els.forEach(load);return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){load(e.target);io.unobserve(e.target)}}),{rootMargin:'420px'});els.forEach(el=>{const r=el.getBoundingClientRect();if(r.top<innerHeight+200)load(el);else io.observe(el)})}
function markerNode(post){const w=document.createTreeWalker(post,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){if(n.nodeValue?.includes('{getToc}'))return n}return null}
function toc(){qa('.post-body').forEach(post=>{if(post.dataset.v4Toc)return;post.dataset.v4Toc='1';const marker=markerNode(post),heads=qa('h2,h3,h4',post).filter(h=>!h.closest('.tbb-v4-toc'));if(heads.length<3){if(marker)marker.nodeValue=marker.nodeValue.replace(/\{getToc\}[^\n]*/i,'');return}const used=new Set(),details=document.createElement('details');details.className='tbb-v4-toc';const raw=marker?.nodeValue||'';const exp=setting(raw,'expanded').toLowerCase();details.open=exp==='true'||exp==='1'||exp==='yes';const summary=document.createElement('summary');summary.textContent=setting(raw,'title')||'Isi Kandungan';const ol=document.createElement('ol');heads.forEach((h,i)=>{let id=h.id||slug(h.textContent),base=id,n=2;while(used.has(id)||(document.getElementById(id)&&document.getElementById(id)!==h))id=base+'-'+n++;used.add(id);h.id=id;const li=document.createElement('li');li.className='toc-'+h.tagName.toLowerCase();const a=document.createElement('a');a.href='#'+id;a.textContent=h.textContent.trim()||('Bahagian '+(i+1));li.append(a);ol.append(li)});details.append(summary,ol);if(marker){const host=marker.parentElement;if(host&&host.childNodes.length===1)host.replaceWith(details);else{marker.nodeValue=marker.nodeValue.replace(/\{getToc\}[^\n]*/i,'');marker.parentNode?.insertBefore(details,marker.nextSibling)}}else{const first=heads[0];first.before(details)}})}
function portableLinks(){qa('.post-body p').forEach(p=>{const a=q(':scope>a',p);if(a&&p.textContent.trim().toLowerCase().startsWith('baca juga'))p.classList.add('tbb-related-link')});qa('.post-body').forEach(post=>{const w=document.createTreeWalker(post,NodeFilter.SHOW_TEXT);const nodes=[];let n;while(n=w.nextNode())if(n.nodeValue?.includes('{getCard}'))nodes.push(n);nodes.forEach(node=>{const t=node.nodeValue,u=setting(t,'url')||setting(t,'link'),title=setting(t,'title')||'Baca artikel berkaitan';const href=safe(u);if(!href)return;const wrap=document.createElement('p');wrap.className='tbb-legacy-card';const a=document.createElement('a');a.href=href;a.textContent=title;wrap.append(a);node.parentNode?.replaceChild(wrap,node)})})}
function tables(){qa('.post-body table').forEach(t=>{if(t.parentElement?.classList.contains('table-responsive-wrapper'))return;const w=document.createElement('div');w.className='table-responsive-wrapper';t.before(w);w.append(t)})}
function toast(msg){const x=document.createElement('div');x.className='tbb-share-toast';x.textContent=msg;document.body.append(x);setTimeout(()=>x.remove(),1800)}
function share(){qa('.post-share').forEach(box=>{if(box.dataset.v4Share)return;box.dataset.v4Share='1';const tools=document.createElement('div');tools.className='tbb-share-tools';const native=document.createElement('button');native.type='button';native.className='tbb-native-share';native.textContent='Kongsi';native.setAttribute('aria-label','Kongsi artikel');native.addEventListener('click',async()=>{const data={title:document.title,text:q('meta[name="description"]')?.content||'',url:location.href};if(navigator.share){try{await navigator.share(data);return}catch(e){if(e.name==='AbortError')return}}panel('share',native)});const copy=document.createElement('button');copy.type='button';copy.className='tbb-copy-share';copy.textContent='Salin pautan';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Pautan disalin')}catch{const ta=document.createElement('textarea');ta.value=location.href;document.body.append(ta);ta.select();document.execCommand('copy');ta.remove();toast('Pautan disalin')}});tools.append(native,copy);box.append(tools)})}
function content(){qa('.post-body img').forEach((img,i)=>{img.decoding='async';if(i>0&&!img.loading)img.loading='lazy';if(!img.hasAttribute('fetchpriority')&&i===0&&img.getBoundingClientRect().top<innerHeight)img.fetchPriority='high'});tables();portableLinks();toc();share()}
function start(){if(!body()||body().dataset.tbbV4)return;body().dataset.tbbV4='1';[menu,panels,dark,images,content].forEach(fn=>{try{fn()}catch(e){console.warn('TBB v4 '+fn.name,e)}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();