/* TBB v4.1 core — navigation, panels, auto TOC, portable links, share, images, a11y. Zero jQuery. */
(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const setting=(t,k)=>String(t||'').match(new RegExp('\\$'+k+'=\\{([^}]*)\\}','i'))?.[1].trim()||'';
const slug=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\u00c0-\u024f\u0600-\u06ff]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,90)||'section';
const safe=u=>{try{const x=new URL(u,location.href);return /^https?:$/.test(x.protocol)?x.href:''}catch{return''}};
const cfg=typeof pbt==='object'&&pbt?pbt:{};
const storage={get:k=>{try{return localStorage.getItem(k)}catch{return null}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch{}}};
const reduced=()=>matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const searchURL=label=>new URL(label&& !['recent','random'].includes(label)?'/search/label/'+encodeURIComponent(label):'/search',location.origin).href;
function tree(nav){if(!nav||nav.dataset.v4Tree)return;nav.dataset.v4Tree='1';const parents=[];[...nav.children].filter(x=>x.tagName==='LI').forEach(li=>{const a=q(':scope>a',li);if(!a)return;const txt=a.textContent.trim(),d=Math.min((txt.match(/^_+/)||[''])[0].length,2);a.textContent=txt.replace(/^_+/,'');const p=parents[d-1];if(d&&p){let ul=q(':scope>ul.sub',p);if(!ul){ul=document.createElement('ul');ul.className='ul sub sm-'+d;p.append(ul)}ul.append(li);p.classList.add('has-sub')}parents[d]=li;parents.length=d+1});nav.closest('.widget')?.classList.add('is-ready')}
function drawerFooter(){const footer=q('.mm-footer');if(!footer||footer.children.length)return;const social=q('.footer-info .social');if(social){const c=social.cloneNode(true);c.className='social color';qa('[id]',c).forEach(x=>x.removeAttribute('id'));qa('.text',c).forEach(x=>x.remove());footer.append(c)}const links=q('.footer-menu ul');if(links){const c=links.cloneNode(true);c.className='links';qa('[id]',c).forEach(x=>x.removeAttribute('id'));footer.append(c)}}
function menu(){const src=q('#main-menu .main-nav')||q('.main-nav');if(src)tree(src);q('#main-menu .widget')?.classList.add('is-ready');const dest=q('.mobile-menu');if(src&&dest&&!dest.children.length){const nav=src.cloneNode(true);nav.className='mobile-nav';qa('[id]',nav).forEach(x=>x.removeAttribute('id'));qa('.has-mega',nav).forEach(li=>{const a=q(':scope>a',li),labels=(setting(a?.dataset.shortcode||'','label')||'').split('/').map(x=>x.trim()).filter(Boolean);q(':scope>.mega',li)?.remove();let sub=q(':scope>ul.sub',li);if(labels.length&&!sub){sub=document.createElement('ul');sub.className='sub';li.append(sub)}labels.forEach(label=>{if(qa(':scope>a',sub||document).some(x=>x.textContent.trim()===label))return;const item=document.createElement('li'),link=document.createElement('a');link.href=searchURL(label);link.textContent=label;item.append(link);sub?.append(item)});li.classList.remove('has-mega','type-mega');if(sub)li.classList.add('has-sub')});qa('ul.sub',nav).forEach(ul=>ul.className='sub');qa('.has-sub>a',nav).forEach(a=>{a.setAttribute('aria-expanded','false');a.addEventListener('click',e=>{const li=a.parentElement;if(!q(':scope>ul.sub',li))return;e.preventDefault();const on=li.classList.toggle('expanded');a.setAttribute('aria-expanded',String(on))})});dest.append(nav)}const logo=q('.main-logo a'),slot=q('.mobile-logo');if(logo&&slot&&!slot.children.length){const c=logo.cloneNode(true);qa('[id]',c).forEach(x=>x.removeAttribute('id'));slot.append(c)}drawerFooter()}
let active=null,returnFocus=null;const focusables=box=>qa('a[href],button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex="0"]',box).filter(x=>x.getClientRects().length);
function panel(name,trigger){const b=document.body;if(!b)return;const open=!!name&&active!==name;b.classList.remove('menu-on','search-on','share-on');qa('.menu-toggle').forEach(x=>x.setAttribute('aria-expanded','false'));if(!open){const f=returnFocus;active=returnFocus=null;f?.focus?.();return}active=name;returnFocus=trigger||document.activeElement;b.classList.add(name+'-on');if(name==='menu')qa('.menu-toggle').forEach(x=>x.setAttribute('aria-expanded','true'));requestAnimationFrame(()=>{const box=q(name==='menu'?'.slide-menu':name==='search'?'.main-search':'.share-modal');focusables(box||document)[0]?.focus()})}
function panels(){qa('.menu-toggle').forEach(x=>x.addEventListener('click',()=>panel('menu',x)));qa('.search-toggle').forEach(x=>x.addEventListener('click',()=>panel('search',x)));qa('.share-toggle,.post-share .show-more button').forEach(x=>x.addEventListener('click',()=>panel('share',x)));qa('.overlay-bg,.hide-mobile-menu,.main-search .close,.hide-modal').forEach(x=>x.addEventListener('click',()=>panel(null)));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active){panel(null);return}if(e.key!=='Tab'||!active)return;const box=q(active==='menu'?'.slide-menu':active==='search'?'.main-search':'.share-modal');if(!box)return;const items=focusables(box);if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}})}
function dark(){const root=document.documentElement,stored=storage.get('tbb_dark_mode')??storage.get('dark_mode');if(cfg.isDark===true||stored==='true')root.classList.add('is-dark');const sync=()=>qa('.darkmode-toggle').forEach(btn=>btn.setAttribute('aria-pressed',String(root.classList.contains('is-dark'))));sync();qa('.darkmode-toggle').forEach(btn=>btn.addEventListener('click',()=>{root.classList.toggle('is-dark');storage.set('tbb_dark_mode',String(root.classList.contains('is-dark')));sync()}))}
function scrollUI(){const header=q('.header-inner'),tops=qa('.to-top');let prev=scrollY,ticking=false;const update=()=>{const y=scrollY;if(header&&cfg.stickyMenu!==false){const fixed=y>header.offsetHeight*2;header.classList.toggle('is-fixed',fixed);header.classList.toggle('show',fixed&&y<prev)}tops.forEach(x=>x.classList.toggle('show',y>=100));prev=y;ticking=false};addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}},{passive:true});tops.forEach(x=>x.addEventListener('click',()=>scrollTo({top:0,behavior:reduced()?'auto':'smooth'})));update()}
function images(){const els=qa('.thumbnail[data-src],.avatar[data-src]');const load=el=>{if(el.dataset.v4Img)return;el.dataset.v4Img='1';const src=safe(el.dataset.src);if(!src)return;const im=new Image();im.decoding='async';if(el.closest('.featured'))im.fetchPriority='high';im.onload=()=>{el.style.backgroundImage='url('+JSON.stringify(im.src)+')';el.classList.add('pbt-lazy')};im.src=src};if(!('IntersectionObserver'in window)){els.forEach(load);return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){load(e.target);io.unobserve(e.target)}}),{rootMargin:'420px'});els.forEach(el=>{const r=el.getBoundingClientRect();if(r.top<innerHeight+200)load(el);else io.observe(el)})}
const SHORT=/\{getToc\}(?:\s+\$[a-zA-Z]+\s*=\s*\{[^}]*\})*/i;
function marker(post){const w=document.createTreeWalker(post,NodeFilter.SHOW_TEXT,{acceptNode:n=>{const p=n.parentElement;if(!p||p.closest('script,style,noscript,.tbb-v4-toc'))return NodeFilter.FILTER_REJECT;return /\{getToc\}/i.test(n.nodeValue||'')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_SKIP}}),n=w.nextNode();if(n){const m=(n.nodeValue||'').match(SHORT);if(m)return{node:n,text:m[0]}}const el=qa('p,div,span',post).find(x=>!x.closest('.tbb-v4-toc')&&/\{getToc\}/i.test(x.textContent||''));if(el){const m=(el.textContent||'').match(SHORT);if(m)return{el,text:m[0]}}return null}
function replaceMarker(m,repl){if(m.node){const t=m.node.nodeValue||'',i=t.indexOf(m.text);if(i<0)return false;const f=document.createDocumentFragment(),before=t.slice(0,i),after=t.slice(i+m.text.length);if(before)f.append(document.createTextNode(before));f.append(repl);if(after)f.append(document.createTextNode(after));m.node.parentNode.replaceChild(f,m.node);return true}if(m.el){if(m.el.textContent.trim()===m.text.trim()){m.el.replaceWith(repl);return true}m.el.innerHTML=m.el.innerHTML.replace(m.text,'');m.el.before(repl);return true}return false}
function toc(){qa('.post-body').forEach(post=>{if(post.dataset.v4Toc)return;const m=marker(post),heads=qa('h2,h3,h4',post).filter(h=>!h.closest('.tbb-v4-toc')&&h.textContent.trim());if(heads.length<3){if(m?.node)m.node.nodeValue=(m.node.nodeValue||'').replace(m.text,'');else m?.el?.remove();post.dataset.v4Toc='1';return}const used=new Set(),details=document.createElement('details');details.className='tbb-v4-toc';const raw=m?.text||'',exp=setting(raw,'expanded').toLowerCase();details.open=['true','1','yes','expanded'].includes(exp);const summary=document.createElement('summary');summary.textContent=setting(raw,'title')||'Isi Kandungan';const ol=document.createElement('ol');heads.forEach((h,i)=>{let id=h.id||slug(h.textContent),base=id,n=2;while(used.has(id)||(document.getElementById(id)&&document.getElementById(id)!==h))id=base+'-'+n++;used.add(id);h.id=id;const li=document.createElement('li');li.className='toc-'+h.tagName.toLowerCase();const a=document.createElement('a');a.href='#'+id;a.textContent=h.textContent.trim()||('Bahagian '+(i+1));li.append(a);ol.append(li)});details.append(summary,ol);if(m)replaceMarker(m,details);else heads[0].before(details);post.dataset.v4Toc='1'})}
function portableLinks(){qa('.post-body p').forEach(p=>{const a=q(':scope>a',p);if(a&&/^baca juga\s*:?/i.test(p.textContent.trim()))p.classList.add('tbb-related-link')});qa('.post-body').forEach(post=>{const w=document.createTreeWalker(post,NodeFilter.SHOW_TEXT),nodes=[];let n;while(n=w.nextNode())if(n.nodeValue?.includes('{getCard}'))nodes.push(n);nodes.forEach(node=>{const t=node.nodeValue,m=t.match(/\{getCard\}(?:\s+\$[a-zA-Z]+\s*=\s*\{[^}]*\})*/i);if(!m)return;const raw=m[0],u=setting(raw,'url')||setting(raw,'link'),title=setting(raw,'title')||'Baca artikel berkaitan',href=safe(u);if(!href)return;const a=document.createElement('a');a.href=href;a.textContent=title;const wrap=document.createElement('p');wrap.className='tbb-legacy-card';wrap.append(a);const host=node.parentElement;if(host&&host.childNodes.length===1)host.replaceWith(wrap);else{node.nodeValue=t.replace(raw,'');node.parentNode?.insertBefore(wrap,node.nextSibling)}})})}
function tables(){qa('.post-body table').forEach(t=>{if(t.parentElement?.classList.contains('table-responsive-wrapper'))return;const w=document.createElement('div');w.className='table-responsive-wrapper';t.before(w);w.append(t)})}
function windows(){qa('a.window-open').forEach(a=>{if(!safe(a.getAttribute('href')))return;a.target='_blank';a.rel='noopener noreferrer'})}
function toast(msg){const x=document.createElement('div');x.className='tbb-share-toast';x.setAttribute('role','status');x.textContent=msg;document.body.append(x);setTimeout(()=>x.remove(),1800)}
function share(){qa('.post-share').forEach(box=>{if(box.dataset.v4Share)return;box.dataset.v4Share='1';const tools=document.createElement('div');tools.className='tbb-share-tools';const native=document.createElement('button');native.type='button';native.className='tbb-native-share';native.textContent='Kongsi';native.setAttribute('aria-label','Kongsi artikel');native.addEventListener('click',async()=>{const data={title:document.title,text:q('meta[name="description"]')?.content||'',url:location.href};if(navigator.share){try{await navigator.share(data);return}catch(e){if(e.name==='AbortError')return}}panel('share',native)});const copy=document.createElement('button');copy.type='button';copy.className='tbb-copy-share';copy.textContent='Salin pautan';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Pautan disalin')}catch{const ta=document.createElement('textarea');ta.value=location.href;document.body.append(ta);ta.select();try{document.execCommand('copy')}catch{}ta.remove();toast('Pautan disalin')}});tools.append(native,copy);box.append(tools)});qa('.copy-link').forEach(box=>{const input=q('input',box),button=q('button',box);if(!input||!button||button.dataset.v4Copy)return;button.dataset.v4Copy='1';button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(input.value)}catch{input.focus();input.select();try{document.execCommand('copy')}catch{}}box.classList.add('copied');setTimeout(()=>box.classList.remove('copied'),2200)})})}
function content(){qa('.post-body img').forEach((img,i)=>{img.decoding='async';if(i>0&&!img.loading)img.loading='lazy';if(i===0&&img.getBoundingClientRect().top<innerHeight)img.fetchPriority='high'});tables();portableLinks();toc();share();windows()}
function start(){const b=document.body;if(!b||b.dataset.tbbV4Core==='4.1.0')return;b.dataset.tbbV4Core='4.1.0';[menu,panels,dark,scrollUI,images,content].forEach(fn=>{try{fn()}catch(e){console.warn('TBB v4 '+fn.name,e)}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();