/* TBB v4 widgets — Blogger feeds, related fallback, mega, search, load-more. Zero jQuery. */
(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const setting=(t,k)=>String(t||'').match(new RegExp('\\$'+k+'=\\{([^}]*)\\}','i'))?.[1].trim()||'';
const origin=location.origin;let jid=0;const cache=new Map();
function searchURL(label='',query=''){const u=new URL(label&&label!=='recent'?'/search/label/'+encodeURIComponent(label):'/search',origin);if(query)u.searchParams.set('q',query);return u.href}
function imgUrl(u,w=720,h=405){if(!u)return'';try{const x=new URL(u,origin);if(/googleusercontent\.com|blogspot\.com|ggpht\.com/.test(x.hostname)){const size=`w${w}-h${h}-p-k-no-nu-rw`;x.pathname=x.pathname.replace(/\/(?:s\d+|w\d+(?:-h\d+)?)(?:-[\w-]+)*\//,'/'+size+'/');let href=x.href;if(/=(?:s|w)\d+/i.test(href))href=href.replace(/=(?:s\d+|w\d+(?:-h\d+)?)(?:-[\w-]+)?$/i,'='+size);return href}return x.href}catch{return''}}
function map(e){const doc=new DOMParser().parseFromString(e.summary?.$t||e.content?.$t||'','text/html');qa('script,style,noscript',doc).forEach(x=>x.remove());const url=e.link?.find(x=>x.rel==='alternate')?.href||'',raw=e.media$thumbnail?.url||q('img',doc)?.getAttribute('src')||'';const d=new Date(e.published?.$t||'');return{id:(e.id?.$t||'').split('post-').pop(),url,thumb:imgUrl(raw),title:e.title?.$t||'Tanpa tajuk',author:e.author?.[0]?.name?.$t||'',category:e.category?.[0]?.term||'',summary:(doc.body?.textContent||'').replace(/\s+/g,' ').trim().slice(0,190),published:Number.isNaN(d.getTime())?'':d.toISOString(),date:Number.isNaN(d.getTime())?'':d.toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'})}}
function feed(label='recent',count=6,query=''){const key=[label,count,query].join('|');if(cache.has(key))return cache.get(key);const p=new Promise((res,rej)=>{const cb='__tbbv4_'+Date.now().toString(36)+'_'+(++jid),s=document.createElement('script'),u=new URL('/feeds/posts/default'+(label&&label!=='recent'?'/-/'+encodeURIComponent(label):''),origin);u.searchParams.set('alt','json-in-script');u.searchParams.set('max-results',String(Math.max(1,Math.min(20,count))));if(query)u.searchParams.set('q',query);u.searchParams.set('callback',cb);let done=false;const clean=()=>{if(done)return;done=true;clearTimeout(to);s.remove();try{delete window[cb]}catch{window[cb]=undefined}};const to=setTimeout(()=>{clean();rej(new Error('feed timeout'))},9000);window[cb]=data=>{try{const posts=(data?.feed?.entry||[]).map(map).filter(x=>x.url);clean();res(posts)}catch(e){clean();rej(e)}};s.onerror=()=>{clean();rej(new Error('feed failed'))};s.async=true;s.src=u.href;document.head.append(s)}).finally(()=>cache.delete(key));cache.set(key,p);return p}
function card(p,full=false,overlay=false){const thumb=`<div class="thumbnail" data-src="${esc(p.thumb)}"></div>`,meta=p.date?`<div class="entry-meta"><span class="entry-time"><time datetime="${esc(p.published)}">${esc(p.date)}</time></span></div>`:'',cat=full&&p.category?`<span class="entry-tag">${esc(p.category)}</span>`:'',summary=full&&!overlay&&p.summary?`<p class="entry-excerpt excerpt">${esc(p.summary)}</p>`:'';return `<article class="post${overlay?' card cs':''}">${overlay?`<a class="entry-inner" href="${esc(p.url)}"><span class="entry-thumbnail">${thumb}</span><div class="entry-header">${cat}<h2 class="entry-title">${esc(p.title)}</h2>${meta}</div></a>`:`<a class="entry-thumbnail" href="${esc(p.url)}" aria-label="${esc(p.title)}">${thumb}</a><div class="entry-header">${cat}<h2 class="entry-title"><a href="${esc(p.url)}">${esc(p.title)}</a></h2>${summary}${meta}</div>`}</article>`}
function render(posts,type){if(!posts.length)return'<p class="error-msg" role="status">Tiada artikel ditemui.</p>';if(type==='story')return`<div class="story-items">${posts.map(x=>card(x,true,true)).join('')}</div>`;if(type==='side')return`<div class="side-items">${posts.map(x=>card(x,false,false)).join('')}</div>`;if(type==='related')return`<div class="related-items">${posts.map(x=>card(x,false,false)).join('')}</div>`;if(type==='mega')return`<div class="mega-items">${posts.map(x=>card(x,false,false)).join('')}</div>`;const first=posts[0],rest=posts.slice(1);if(type==='block2')return`<div class="block2-items">${card(first,true,true)}<div class="block2-grid">${rest.map(x=>card(x,true,false)).join('')}</div></div>`;return`<div class="block1-items">${card(first,true,false)}<div class="block1-list">${rest.map(x=>card(x,false,false)).join('')}</div></div>`}
function hydrateImages(root){qa('.thumbnail[data-src],.avatar[data-src]',root).forEach(el=>{if(el.dataset.v4Img)return;el.dataset.v4Img='1';const src=el.dataset.src;if(!src)return;const im=new Image();im.decoding='async';im.onload=()=>{el.style.backgroundImage='url('+JSON.stringify(im.src)+')';el.classList.add('pbt-lazy')};im.src=src})}
async function load(target,{label='recent',count=5,type='block1',exclude=''}={}){if(!target||target.dataset.v4State==='loading'||target.dataset.v4State==='loaded')return;target.dataset.v4State='loading';target.setAttribute('aria-busy','true');try{let posts=await feed(label,count+(exclude?2:0));posts=posts.filter(x=>x.id!==String(exclude));target.innerHTML=render(posts.slice(0,count),type);target.dataset.v4State='loaded';hydrateImages(target)}catch(e){target.dataset.v4State='error';target.innerHTML='<p class="error-msg" role="status">Artikel belum dapat dimuatkan.</p>';console.warn('TBB v4 feed',e)}finally{target.removeAttribute('aria-busy')}}
async function related(target,label,count,exclude){target.dataset.v4State='loading';target.setAttribute('aria-busy','true');try{const seen=new Set(),all=[];for(const l of [...new Set([label,'recent'].filter(Boolean))]){let batch=[];try{batch=await feed(l,Math.min(20,count+5))}catch{}for(const p of batch){const key=p.id||p.url;if(p.id===String(exclude)||seen.has(key))continue;seen.add(key);all.push(p);if(all.length>=count)break}if(all.length>=count)break}target.innerHTML=render(all,'related');target.dataset.v4State='loaded';hydrateImages(target)}catch{target.innerHTML='<p class="error-msg">Tiada artikel berkaitan.</p>';target.dataset.v4State='error'}finally{target.removeAttribute('aria-busy')}}
function feeds(){const io='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const fn=e.target.__v4job;fn?.();io.unobserve(e.target)}}),{rootMargin:'420px'}):null;const queue=(t,fn)=>{if(!io||t.closest('.featured'))fn();else{t.__v4job=fn;io.observe(t)}};qa('.getPosts .widget-content[data-shortcode]').forEach(t=>{const code=t.dataset.shortcode||'',type=t.closest('.sidebar,.footer,.site-footer')?'side':setting(code,'type')||'block1',label=setting(code,'label')||'recent',count=Math.max(1,Math.min(12,parseInt(setting(code,'results'),10)||({story:3,side:4,block2:5}[type]||5)));const link=t.closest('.widget')?.querySelector('.title-link');if(link)link.href=searchURL(label);queue(t,()=>load(t,{label,count,type}))});qa('.related-wrap').forEach(w=>{const tag=q('.related-tag',w),t=q('.widget-content',w);if(!tag||!t)return;const code=q('#related-posts .HTML')?.dataset.shortcode||'',count=Math.max(1,Math.min(12,parseInt(setting(code,'results'),10)||6)),chosen=setting(code,'label'),label=chosen&&chosen!=='related'?chosen:(tag.dataset.label||'recent');const link=q('.title-link',w);if(link)link.href=searchURL(label);queue(t,()=>related(t,label,count,tag.dataset.id))})}
function mega(){qa('.main-nav .has-mega>a[data-shortcode]').forEach(a=>{const li=a.parentElement,labels=(setting(a.dataset.shortcode,'label')||'recent').split('/').map(x=>x.trim()).filter(Boolean),box=q(':scope>.mega .container',li);if(!box)return;let target=q('.tbb-v4-mega',box);if(!target){target=document.createElement('div');target.className='tbb-v4-mega';box.append(target)}const go=()=>load(target,{label:labels[0]||'recent',count:5,type:'mega'});li.addEventListener('pointerenter',go,{once:true});li.addEventListener('focusin',go,{once:true})})}
function search(){const box=q('.main-search'),input=box&&q('input',box),results=box&&q('.search-results',box);if(!input||!results)return;let timer=0,seq=0;results.setAttribute('aria-live','polite');input.addEventListener('keydown',e=>{if(e.key==='Enter'&&input.value.trim()){e.preventDefault();location.href=searchURL('',input.value.trim())}});input.addEventListener('input',()=>{clearTimeout(timer);const query=input.value.trim(),id=++seq;results.innerHTML='';if(!query)return;timer=setTimeout(async()=>{try{const posts=await feed('recent',7,query);if(id!==seq)return;results.innerHTML=`<div class="search-items">${posts.map(x=>card(x,false,false)).join('')}</div>`;hydrateImages(results)}catch{}},260)})}
function loadMore(){const btn=q('#load-more'),target=q('.blog-posts');if(!btn||!target)return;btn.addEventListener('click',async e=>{e.preventDefault();if(btn.dataset.busy)return;const url=btn.dataset.url||btn.href;if(!url)return;btn.dataset.busy='1';try{const r=await fetch(url,{credentials:'omit'});if(!r.ok)throw 0;const d=new DOMParser().parseFromString(await r.text(),'text/html'),incoming=q('.blog-posts',d),next=q('#load-more',d);if(!incoming)throw 0;qa(':scope>.post:not(.ad-type)',incoming).forEach(p=>{qa('script',p).forEach(x=>x.remove());target.append(document.importNode(p,true))});hydrateImages(target);const n=next?.dataset.url||next?.getAttribute('href');if(n){btn.dataset.url=n;btn.href=n}else btn.remove()}catch{location.href=url}finally{delete btn.dataset.busy}})}
function start(){if(document.body?.dataset.v4Widgets)return;document.body.dataset.v4Widgets='1';[feeds,mega,search,loadMore].forEach(fn=>{try{fn()}catch(e){console.warn('TBB v4 '+fn.name,e)}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();